Repository smaranjitghose/ArtCV, pull requests merged in 2020-10, with the labels that each got.

#20 Glitch art
  README.MD
  assets/glitched_kolkata.jpg
  glitch_art.py
Labels: hacktoberfest_accepted

#21 Cartoon effect
  assets/black_and_wihte_cartoon.jpg
  assets/cartoon1.jpg
  assets/comic_cartoon_effect.jpg
  cartoon_effects.py
  comic_cartoon_effect.py
Labels: hacktoberfest_accepted

#27 Sobel Edge detection
  README.MD
  assets/sobel_filter.JPG
  glitch_art.py
  sobel_filter.py
Labels: PR: reviewed-approved, hacktoberfest_accepted

#28 Exception Handling and improvements to prevent crashes
  oil_painting.py
  pencil_sketch.py
  pointilism.py
Labels: PR: unreviewed, hacktoberfest_accepted

#30 Anime Vintage Effect
  anime_effect.py
  assets/anime_blue_effect.jpg
  assets/anime_effect.jpg
  assets/anime_predatorView_effect.jpg
  assets/anime_vintage_effect.jpg
Labels: hacktoberfest_accepted

#31 Emboss Effect
  README.MD
  assets/emboss_effect_coloured.jpg
  assets/emboss_effect_grayscale.jpg
  emboss_effect.py
Labels: PR: unreviewed, hacktoberfest_accepted

#35 Motion Blur
  README.MD
  assets/diagonalBlur.jpg
  assets/horizontalBlur.jpg
  assets/verticalBlur.jpg
  motion_blur.py
Labels: hacktoberfest_accepted
