Repository smaranjitghose/ArtCV, pull requests merged in 2021-01, with the labels that each got.

#47 Added progress bars.
  oil_painting.py
  pencil_sketch.py
  requirements.txt
  water_coloring.py
Labels: Easy, SWoC2021

#51 Add Mosaic Script + Assets
  assets/mosaic/filler_images/20200420 202959_horse.jpg
  assets/mosaic/filler_images/20200420 203811_artwork.jpg
  assets/mosaic/filler_images/20200420 203845_artwork.jpg
  assets/mosaic/filler_images/20200420 204425_artwork.jpg
  assets/mosaic/filler_images/20200420 204818_picsum.jpg
  assets/mosaic/main_image/img.jpg
  mosaic.py
Labels: Hard, SWoC2021

#52 Add ASCII Art Script
  Ascii-Image-Art.py
Labels: Intermediate, SWoC2021
